# Generated by Django 4.2 on 2025-06-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices_app', '0005_alter_users_contact_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('grocery', 'Grocery'), ('electricals', 'Electricals'), ('plumbing', 'Plumbing')], max_length=20)),
                ('subcategory', models.CharField(blank=True, choices=[('dairy', 'Dairy & Eggs'), ('snacks', 'Snacks & Branded Foods'), ('beverages', 'Beverages'), ('bakery', 'Bakery & Biscuits'), ('breakfast', 'Breakfast & Instant Food'), ('staples', 'Staples'), ('sweets', 'Sweets & Chocolates'), ('bulbs', 'Bulbs & Tubelights'), ('switches', 'Switches & Sockets'), ('wires', 'Wires & Cables'), ('appliances', 'Small Appliances'), ('batteries', 'Batteries & Chargers'), ('pipes', 'Pipes & Fittings'), ('taps', 'Taps & Faucets'), ('showers', 'Showers & Accessories'), ('tools', 'Tools & Adhesives')], max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
