# Generated by Django 4.2 on 2025-06-20 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices_app', '0006_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('grocery', 'Grocery'), ('electricals', 'Electricals'), ('plumbing', 'Plumbing')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('fruits_vegetables', 'Fruits & Vegetables'), ('dairy_bakery', 'Dairy & Bakery'), ('beverages', 'Beverages'), ('snacks', 'Snacks'), ('household', 'Household'), ('personal_care', 'Personal Care'), ('lighting', 'Lighting'), ('kitchen_appliances', 'Kitchen Appliances'), ('electronics', 'Electronics'), ('tools', 'Tools'), ('pipes_fittings', 'Pipes & Fittings'), ('faucets', 'Faucets'), ('bathroom', 'Bathroom'), ('kitchen_plumbing', 'Kitchen Plumbing')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='HomeServices_app.shop'),
        ),
    ]
