# Generated by Django 4.2 on 2025-06-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices_app', '0007_shop_alter_product_options_product_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop_images/'),
        ),
    ]
