# Generated by Django 4.2 on 2025-06-21 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices_app', '0010_adminregistrationrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminregistrationrequest',
            name='reason_for_registration',
        ),
    ]
