# Generated by Django 4.2 on 2025-06-21 06:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices_app', '0011_remove_adminregistrationrequest_reason_for_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminregistrationrequest',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Indian mobile number (10 digits starting with 6, 7, 8, or 9).', regex='^[6-9]\\d{9}$')]),
        ),
    ]
