# Generated by Django 4.2 on 2025-06-23 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices_app', '0013_adminregistrationrequest_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecatogarys',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
