# Generated by Django 4.2 on 2025-06-25 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices_app', '0016_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='city',
        ),
    ]
